name: Hokkaido_Snow_Moisture
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - rioxarray
  - xarray
  - geopandas
  - matplotlib
  - cartopy
  - jupyterlab
  - ipykernel
  - pathlib
